---
- hosts: ip76
  remote_user: adminer
  become: yes

  tasks:
  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - geogebra    # geogebra
      - squeak-vm   # scratch
      - veyon       # remote control
      - openssh-server   # ssh remotely
      - gimp        # image editor
      - josm        # maps
      - marble      # maps
      - gnome-maps  # maps
      - python-pip  # for gsettings
  - pip:
      name: psutil

  - name: Ensure group "user" exists
    group:
      name: user
      state: present

  - name: Add the user 'user'
    user:
      name: user
      comment: User
      group: user
      password: $6$ip76$nrQpcvpuoVJoFjBNoPsFeRRe8XbfEklp2M8.xkTKylaGZj2Ta6hxstKFghF2Dow3HNumNen30/9TDiQy.kNro/
