---
-
  hosts: ip172
  remote_user: user
  become: no

# https://github.com/gantsign/ansible-role-pin-to-launcher
  # roles:
    # - role: gantsign.pin-to-launcher
    #   pin_to_launcher: gnome
    #   pin_to_launcher_favorites:
    #     - application 'libreoffice-math.desktop'

  vars:
     contents: "{{ lookup('file', 'favorites') }}"

  tasks:
    - name: set desktop icons
      dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "{{ contents }}"
        state: present

    - name: Configure available keyboard layouts in Gnome
      dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'de'), ('xkb', 'us')]"
        state: present

    - name: Read currently available keyboard layouts in Gnome
      dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        state: read
      register: keyboard_layouts
